name: Checkmarx AST Scan
on:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Checkmarx AST CLI Action
        uses: checkmarx/ast-github-action@2.0.9 #Github Action version
        with:
          base_uri: https://deu.ast.checkmarx.net/
          cx_tenant: cx_emea_ses_canary_kishor_hasurkar_canar
          cx_client_id: ${{ secrets.CLIENT_ID }}
          cx_client_secret: ${{ secrets.SECRET }}
          additional_params: --debug 
